-- MySQL Script generated by MySQL Workbench
-- jue 25 may 2023 09:29:22
-- Model: New Model    Version: 1.0

-- -----------------------------------------------------
-- Schema elretenciondb
-- -----------------------------------------------------
-- base de datos de registros de retenciones a IVA y ISLR sobre razones sociales

-- -----------------------------------------------------
-- Schema eladmindb
--
-- admin shcema for common data
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `elretenciondb`.`reten_retenciones_registros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elretenciondb`.`reten_retenciones_registros` ;

CREATE TABLE IF NOT EXISTS `elretenciondb`.`reten_retenciones_registros` (
  `cod_retencion` VARCHAR(40) NOT NULL COMMENT 'YYYYMMDDHHMMSS codigo unico de retencion interno',
  `num_comprobante` VARCHAR(40) NULL COMMENT 'YYYYMMDD+NNNNNNNN numero unico desde el seniat',
  `fecha_operacion_retencion` VARCHAR(40) NULL COMMENT 'YYYYMMDD del comprobante despues de declarar',
  `fecha_periodo_fiscal` VARCHAR(40) NULL COMMENT 'YYYYMM de la fecha de la retencion',
  `cod_juridico_retencion` VARCHAR(40) NULL COMMENT 'rif del agente de retencion',
  `cod_juridico_retenido` VARCHAR(40) NULL COMMENT 'rif del agente a retener',
  `mon_objeto_retencion` DECIMAL(40,2) NULL COMMENT 'monto operacion que es el monto menos el iva',
  `num_porcentaje_tasa` SMALLINT NULL DEFAULT 0 COMMENT 'tasa en porcentage retenido en dicho caso\n',
  `mon_retenido_iva_o_islr` DECIMAL(40,2) NULL DEFAULT 0.0 COMMENT 'monto del IVA o de la retencion si es ISLR',
  `mon_retencion_acumulada` DECIMAL(40,2) NULL DEFAULT 0.0 COMMENT 'cantidad de objeto de retencion acumulada',
  `mon_retenido_iva_o_acumulado` DECIMAL(40,2) NULL DEFAULT 0.0,
  `tipo_retencion` VARCHAR(40) NULL COMMENT 'IVA O ISLR',
  `sessionflag` VARCHAR(40) NULL COMMENT 'YYYYMMDDhhmmss.entidad.usuario quien altero',
  `sessionficha` VARCHAR(40) NULL COMMENT 'YYYYMMDDhhmmss.entidad.usuario quien creo',
  PRIMARY KEY (`cod_retencion`))
COMMENT = 'tabla centralizada de registros de retenciones';


-- -----------------------------------------------------
-- Table `elretenciondb`.`reten_facturas_retenciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elretenciondb`.`reten_facturas_retenciones` ;

CREATE TABLE IF NOT EXISTS `elretenciondb`.`reten_facturas_retenciones` (
  `orden_operacion` VARCHAR(40) NOT NULL COMMENT 'numero de operacion',
  `cod_retencion` VARCHAR(40) NOT NULL COMMENT 'retencion asociada',
  `cod_factura` VARCHAR(40) NOT NULL COMMENT 'fatura asociada a la retencion',
  `sessionflag` VARCHAR(40) NULL COMMENT 'YYYYMMDDhhmmss.entidad.usuario quien altero',
  `sessionficha` VARCHAR(40) NULL COMMENT 'YYYYMMDDhhmmss.entidad.usuario quien creo',
  PRIMARY KEY (`cod_retencion`, `cod_factura`))
COMMENT = 'cuantas facturas tiene cada retencion';


-- -----------------------------------------------------
-- Table `eladmindb`.`adm_facturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eladmindb`.`adm_facturas` ;

CREATE TABLE IF NOT EXISTS `eladmindb`.`adm_facturas` (
  `cod_factura` VARCHAR(40) NOT NULL COMMENT 'YYYYMMDD+NNNNNN  fecha_factura + num_factura',
  `num_factura` VARCHAR(40) NOT NULL COMMENT 'numero de la factura, numero unico del talonario o de la factura',
  `num_control` VARCHAR(40) NULL COMMENT 'numero de control en la factura, sino numero caja o empleado que vende',
  `cod_juridico_emisor` VARCHAR(40) NULL COMMENT 'rif del que emite la factura',
  `cod_juridico_recepcion` VARCHAR(40) NULL COMMENT 'rif del que se le hace la factura',
  `mon_factura_factura` DECIMAL(40,2) NULL DEFAULT 0.0 COMMENT 'cantida pagada en factura monto de la factura sin retener',
  `mon_factura_excento` DECIMAL(40,2) NULL DEFAULT 0.0 COMMENT 'cantida pagada en factura monto de la factura de los excento',
  `mon_factura_moneda` VARCHAR(40) NOT NULL DEFAULT 'VES' COMMENT 'codigo iso moneda enque esta la factura',
  `sessionflag` VARCHAR(40) NULL COMMENT 'YYYYMMDDhhmmss.entidad.usuario quien altero',
  `sessionficha` VARCHAR(40) NULL COMMENT 'YYYYMMDDhhmmss.entidad.usuario quien creo',
  PRIMARY KEY (`cod_factura`))
COMMENT = 'registro de facturas manejadas en todos los sistemas';


-- -----------------------------------------------------
-- Table `elretenciondb`.`reten_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elretenciondb`.`reten_usuarios` ;

CREATE TABLE IF NOT EXISTS `elretenciondb`.`reten_usuarios` (
  `username` VARCHAR(40) NOT NULL COMMENT 'login del usuario, id del correo para este sistema especifico',
  `userkey` VARCHAR(40) NULL COMMENT 'sincronia con al calve del usuario',
  `userstatus` VARCHAR(40) NULL COMMENT 'ACTIVO|INACTIVO',
  `sessionflag` VARCHAR(40) NULL COMMENT 'YYYYMMDDhhmmss.entidad.usuario quien altero',
  `sessionficha` VARCHAR(40) NULL COMMENT 'YYYYMMDDhhmmss.entidad.usuario quien creo',
  PRIMARY KEY (`username`))


-- -----------------------------------------------------
-- Table `elretenciondb`.`reten_usuarios_modulos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elretenciondb`.`reten_usuarios_modulos` ;

CREATE TABLE IF NOT EXISTS `elretenciondb`.`reten_usuarios_modulos` (
  `username` VARCHAR(40) NOT NULL,
  `modulo_string` VARCHAR(40) NOT NULL DEFAULT 'ALL',
  `sessionflag` VARCHAR(40) NULL COMMENT 'YYYYMMDDhhmmss.entidad.usuario quien altero',
  `sessionficha` VARCHAR(40) NULL COMMENT 'YYYYMMDDhhmmss.entidad.usuario quien creo',
  PRIMARY KEY (`username`, `modulo_string`))
COMMENT = 'permiso granular en que modulo opera el usuario, si esta lis' /* comment truncated */ /*tado, permite vista, sino manda un mensaje*/;

-- -----------------------------------------------------
-- Table `eladmindb`.`adm_juridico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eladmindb`.`adm_juridico` ;

CREATE TABLE IF NOT EXISTS `eladmindb`.`adm_juridico` (
  `cod_juridico` VARCHAR(40) NOT NULL COMMENT 'RIF registro de informacion fiscal',
  `cod_denominacion` VARCHAR(40) NULL COMMENT 'subjetiva (asociacion) o objetiva (nombre fantasia)',
  `nombre_legal` VARCHAR(40) NULL COMMENT 'primer nombre el representante o nombre de fantasia si es denominacion objetiva',
  `nombre_comercial` VARCHAR(40) NULL COMMENT 'nombre que se muestra al publico o comercial',
  `direccion_comercial` VARCHAR(40) NULL COMMENT 'direccion que se muestra al publico o comercial',
  `tipo_juridico` VARCHAR(40) NULL COMMENT 'NATURAL|JURIDICA|GUBERNAMENTAL',
  `ficha` VARCHAR(40) NULL COMMENT 'el representante legal primario desde intranet',
  `sessionflag` VARCHAR(40) NULL COMMENT 'YYYYMMDDhhmmss.entidad.usuario quien altero',
  `sessionficha` VARCHAR(40) NULL COMMENT 'YYYYMMDDhhmmss.entidad.usuario quien creo',
  PRIMARY KEY (`cod_juridico`))
COMMENT = 'tabla razones sociales.. todos los rif usados aqui clientes ' /* comment truncated */ /*o empresas*/;



